"""
send_notification.py
Sends the Africa Properties weekly dashboard notification email via Outlook.
Runs automatically every Monday & Friday at 12:30 PM.

The MTD snapshot image is pre-generated by take_snapshot.py (called from
publish.bat right after each git push).  This script never runs Playwright —
it just reads the saved PNG file, keeping the email step fast and reliable.

To:  Abdulla Aujan, Dave Anderson, Elena Son
CC:  Muhammad Moiz Siddiqui, Glenda Gallego, Ghufran Mumtaz, Benoit Haas
"""

import sys, datetime, base64, os
import win32com.client

DASHBOARD_URL  = "https://benoit-aujan.github.io/africa-dashboard/"
SNAPSHOT_PATH  = os.path.join(os.path.dirname(os.path.abspath(__file__)), "mtd_snapshot.png")
SNAPSHOT_MAX_AGE_DAYS = 7   # warn (but still send) if snapshot is older than this

TO = [
    "Abdulla Aujan <Abdulla.Aujan@aujan.com>",
    "Dave Anderson <dave.anderson@aujan.com>",
    "Elena Son <elena.son@aujan.com>",
]
CC = [
    "Muhammad Moiz Siddiqui <moiz.siddiqui@aujan.com>",
    "Glenda Gallego <Glenda.Gallego@aujan.com>",
    "Ghufran Mumtaz <ghufran.mumtaz@aujan.com>",
    "Benoit Haas <benoit.haas@aujan.com>",
]

SUBJECT = "Africa Properties — Daily Sales Dashboard update"


def load_snapshot():
    """
    Reads the pre-saved MTD snapshot (written by take_snapshot.py via publish.bat).
    Returns (base64_string, age_days) or ("", None) if the file is missing.
    """
    if not os.path.exists(SNAPSHOT_PATH):
        print("  WARNING: mtd_snapshot.png not found — sending without image.")
        print("  (Run 'python scripts/take_snapshot.py' to generate it.)")
        return "", None

    mtime    = os.path.getmtime(SNAPSHOT_PATH)
    age_days = (datetime.datetime.now().timestamp() - mtime) / 86400
    size     = os.path.getsize(SNAPSHOT_PATH)

    if age_days > SNAPSHOT_MAX_AGE_DAYS:
        print(f"  WARNING: snapshot is {age_days:.1f} days old ({size:,} bytes) — "
              f"using it anyway but check publish.bat / take_snapshot.py.")
    else:
        print(f"  Snapshot loaded: {size:,} bytes, {age_days:.1f}d old.")

    with open(SNAPSHOT_PATH, "rb") as f:
        return base64.b64encode(f.read()).decode("ascii"), age_days


def build_html(img_b64):
    """Returns the full HTML email body."""

    img_tag = (
        f'<img src="data:image/png;base64,{img_b64}" '
        f'width="966" style="display:block;max-width:100%;border-radius:8px;'
        f'margin:16px 0;" alt="Africa Properties MTD Summary">'
        if img_b64 else ""
    )

    return f"""\
<html>
<head>
<style>
  body, p, td, li {{
    font-family: Aptos, Calibri, Arial, sans-serif;
    font-size: 12pt;
    color: #1f2937;
    line-height: 1.6;
  }}
  .disclaimer {{
    font-style: italic;
    font-size: 12pt;
    color: #6b7280;
    border-bottom: 1px solid #e5e7eb;
    padding-bottom: 10px;
    margin-bottom: 18px;
  }}
  a {{ color: #1d4ed8; }}
</style>
</head>
<body>
<p class="disclaimer">Disclaimer: This email is automatically generated by Claude AI.</p>

<p>Dear All,</p>

<p>Reminder that the Africa daily sales dashboard is updated for last week.</p>

<p><strong>&#128279; Dashboard link:</strong>
<a href="{DASHBOARD_URL}">{DASHBOARD_URL}</a></p>

{img_tag}

<p>The report is updated automatically each day at 12pm midday (UAE time).
Should you have any questions on the figures, please do not hesitate to reach out.</p>

<p>Best regards,<br>
Benoit</p>

</body>
</html>
"""


def main(draft_only=False):
    # 1. Load the pre-saved snapshot (taken by take_snapshot.py during publish)
    print("Loading dashboard snapshot...")
    img_b64, age = load_snapshot()
    if img_b64:
        print(f"  Snapshot encoded: {len(img_b64)//1024} KB")

    # 2. Connect to Outlook
    try:
        outlook = win32com.client.Dispatch("Outlook.Application")
    except Exception as e:
        print(f"ERROR: Cannot connect to Outlook: {e}")
        sys.exit(1)

    # 3. Build and send / save draft
    mail          = outlook.CreateItem(0)
    mail.To       = "; ".join(TO)
    mail.CC       = "; ".join(CC)
    mail.Subject  = SUBJECT
    mail.HTMLBody = build_html(img_b64)

    if draft_only:
        mail.Save()
        print(f"[{datetime.datetime.now():%Y-%m-%d %H:%M}] Draft saved to Outlook Drafts.")
    else:
        mail.Send()
        print(f"[{datetime.datetime.now():%Y-%m-%d %H:%M}] Email sent to {len(TO)} recipients ({len(CC)} CC).")


if __name__ == "__main__":
    import argparse
    p = argparse.ArgumentParser()
    p.add_argument("--draft", action="store_true", help="Save as Outlook draft instead of sending")
    args = p.parse_args()
    main(draft_only=args.draft)
