"""
send_notification.py
Sends the Africa Properties weekly dashboard notification email via Outlook.
Runs automatically every Monday at 12:15 PM, after the 12:00 PM data refresh.

To:  Abdulla Aujan, Dave Anderson, Elena Son
CC:  Muhammad Moiz Siddiqui, Glenda Gallego, Ghufran Mumtaz, Benoit Haas
"""

import sys, datetime, base64, os, tempfile
import win32com.client

DASHBOARD_URL = "https://benoit-aujan.github.io/africa-dashboard/"
SNAPSHOT_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "mtd_snapshot.png")

TO = [
    "Abdulla Aujan <Abdulla.Aujan@aujan.com>",
    "Dave Anderson <dave.anderson@aujan.com>",
    "Elena Son <elena.son@aujan.com>",
]
CC = [
    "Muhammad Moiz Siddiqui <moiz.siddiqui@aujan.com>",
    "Glenda Gallego <Glenda.Gallego@aujan.com>",
    "Ghufran Mumtaz <ghufran.mumtaz@aujan.com>",
    "Benoit Haas <benoit.haas@aujan.com>",
]

SUBJECT = "Africa Properties — Daily Sales Dashboard update"


def take_screenshot():
    """
    Opens the live dashboard in headless Chrome, sets the correct slicers
    (Weekly view, Var Abs/Ppt, current month), then screenshots the MTD cards.
    Retries up to 3 times with a 30-second gap to handle GitHub Pages deployment lag.
    """
    MAX_ATTEMPTS = 3
    RETRY_WAIT_MS = 30_000   # 30 s between attempts

    for attempt in range(1, MAX_ATTEMPTS + 1):
        try:
            from playwright.sync_api import sync_playwright
            with sync_playwright() as p:
                browser = p.chromium.launch(headless=True)
                page = browser.new_page(viewport={"width": 1280, "height": 900})

                # Wait for the page AND its network requests (data.json) to finish
                page.goto(DASHBOARD_URL, wait_until="networkidle", timeout=30_000)
                page.wait_for_timeout(3000)   # let JS render after data loads

                # Ensure correct slicers are active
                page.locator("#btn-weekly").click()        # Weekly view
                page.locator("#btn-var-abs").click()       # Var Abs / Ppt
                page.wait_for_timeout(800)                 # let tables re-render

                # Navigate to current month: click › until period label matches
                today = datetime.date.today()
                target = today.strftime("%B %Y")           # e.g. "April 2026"
                for _ in range(24):                        # max 24 clicks forward/back
                    label = page.locator("#period-label").inner_text()
                    if label == target:
                        break
                    page.locator("button:has-text('›')").click()
                    page.wait_for_timeout(200)

                page.wait_for_timeout(500)
                mtd = page.locator(".mtd-section")
                mtd.screenshot(path=SNAPSHOT_PATH)
                browser.close()
            print(f"  Screenshot OK (attempt {attempt})")
            return True

        except Exception as e:
            print(f"  WARNING: screenshot attempt {attempt}/{MAX_ATTEMPTS} failed: {e}")
            if attempt < MAX_ATTEMPTS:
                print(f"  Retrying in 30 s...")
                import time
                time.sleep(30)

    print("  All screenshot attempts failed — sending without image.")
    return False


def build_html(img_b64):
    """Returns the full HTML email body."""

    img_tag = (
        f'<img src="data:image/png;base64,{img_b64}" '
        f'width="966" style="display:block;max-width:100%;border-radius:8px;'
        f'margin:16px 0;" alt="Africa Properties MTD Summary">'
        if img_b64 else ""
    )

    return f"""\
<html>
<head>
<style>
  body, p, td, li {{
    font-family: Aptos, Calibri, Arial, sans-serif;
    font-size: 12pt;
    color: #1f2937;
    line-height: 1.6;
  }}
  .disclaimer {{
    font-style: italic;
    font-size: 12pt;
    color: #6b7280;
    border-bottom: 1px solid #e5e7eb;
    padding-bottom: 10px;
    margin-bottom: 18px;
  }}
  a {{ color: #1d4ed8; }}
</style>
</head>
<body>
<p class="disclaimer">Disclaimer: This email is automatically generated by Claude AI.</p>

<p>Dear All,</p>

<p>Reminder that the Africa daily sales dashboard is updated for last week.</p>

<p><strong>&#128279; Dashboard link:</strong>
<a href="{DASHBOARD_URL}">{DASHBOARD_URL}</a></p>

{img_tag}

<p>The report is updated automatically each day at 12pm midday (UAE time).
Should you have any questions on the figures, please do not hesitate to reach out.</p>

<p>Best regards,<br>
Benoit</p>

</body>
</html>
"""


def main(draft_only=False):
    # 1. Take fresh screenshot
    print("Taking dashboard screenshot...")
    ok = take_screenshot()

    img_b64 = ""
    if ok and os.path.exists(SNAPSHOT_PATH):
        with open(SNAPSHOT_PATH, "rb") as f:
            img_b64 = base64.b64encode(f.read()).decode("ascii")
        print(f"  Screenshot encoded ({len(img_b64)//1024} KB)")
    else:
        print("  No screenshot — sending without image.")

    # 2. Connect to Outlook
    try:
        outlook = win32com.client.Dispatch("Outlook.Application")
    except Exception as e:
        print(f"ERROR: Cannot connect to Outlook: {e}")
        sys.exit(1)

    # 3. Build and send / save draft
    mail          = outlook.CreateItem(0)
    mail.To       = "; ".join(TO)
    mail.CC       = "; ".join(CC)
    mail.Subject  = SUBJECT
    mail.HTMLBody = build_html(img_b64)

    if draft_only:
        mail.Save()
        print(f"[{datetime.datetime.now():%Y-%m-%d %H:%M}] Draft saved to Outlook Drafts.")
    else:
        mail.Send()
        print(f"[{datetime.datetime.now():%Y-%m-%d %H:%M}] Email sent to {len(TO)} recipients ({len(CC)} CC).")


if __name__ == "__main__":
    import argparse
    p = argparse.ArgumentParser()
    p.add_argument("--draft", action="store_true", help="Save as Outlook draft instead of sending")
    args = p.parse_args()
    main(draft_only=args.draft)
